### ISSUE TITLE
Dicom Store studies not getting loaded

### ISSUE THREAD

**Issue by capt2101akash** [OsiriX-Foundation/KheopsOrchestration#1] opened 2020-05-01 21:10 UTC
Hi, I am trying to integrate kheops with Dicom Store but the study is not getting loaded and throwing an error called an error occurred. Can someone give some insights on that.

**Comment by spalte** [comment] 2020-05-01 21:39
Hi,

I’m sorry you are running into trouble. I’d like to help, but I don’t really understand what is happening from your question. Could you tell me a bit more about your setup and what your are trying to do?

Joël

**Comment by capt2101akash** [comment] 2020-05-01 21:46
Sure, I am trying to integrate GCP dicom into kheops viewer. I followed the steps and procedure provided by you in the read me but I am having trouble getting the studies from the dicom store. The studies are not getting loaded and are showing an error occurred. PFA screenshot
<img width="935" alt="kheops_error" src="https://user-images.githubusercontent.com/16082168/80843963-2c1c0800-8c23-11ea-9ddd-57b1b456241b.PNG">

You can also visit the demo site

**Comment by capt2101akash** [comment] 2020-05-02 06:32
@spalte Any Views on the above problem?

**Comment by spalte** [comment] 2020-05-02 09:05
I haven’t been able to connect to kheops.tk. Is it up?

It’s hard to say what is going wrong from just the above screenshot. Since you are getting timeouts, I suspect that some of the Deployments are not responding because they failed on startup. But I can’t say more than that.

I have not yet had the opportunity to update the GCP example to version 0.9.4 of KHEOPS. There have been quite a few changes, especially with the interaction with Keycloak. I will try to update the GCP example early next week, and add some more GCP configuration guidance. I suspect the issue is likely in the GCP configuration.

**Comment by capt2101akash** [comment] 2020-05-02 09:15
Hey @spalte the url is kheops.tk:3000 sorry my bad forgot to add the port number in the previous message. Have a look at it and will be waiting for your updates after that.
Thanks.

**Comment by nikpap** [comment] 2021-07-09 08:24
Closing this issue as `kheops.tk:3000` is not working, feel free to reply if the issue is still ongoing.

**Closed by nikpap** 2021-07-09 08:24 UTC
